language: node_js
node_js:
  - "8"

# whitelisted branches
branches:
  only:
    - master

script: "npm test"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
